version: "3"
services:
  web:
    image: kkti4216/webrtc-web:latest
    container_name: webrtc-web

  signal:
    image: kkti4216/webrtc-sig:linux
    container_name: webrtc-sig
    volumes:
      - ./ayame/ayame.ini:/app/ayame.ini
      - ./var/log/ayame:/var/log/ayame

  https-portal:
    image: steveltn/https-portal:1.22
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'webrtc.itokoki.hongo.wide.ad.jp -> http://web:5555, signaling.itokoki.hongo.wide.ad.jp -> http://signal:3333/signaling'
      WEBSOCKET: "true"
      STAGE: 'production'
      LISTEN_IPV6: 'true'
      ERROR_LOG: default
      ACCESS_LOG: default
    volumes:
      - ./data/ssl_certs:/var/lib/https-portal
      - ./var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro


networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:c0ff:ee::/64
          gateway: fd00:c0ff:ee::1

